### ISSUE TITLE
Install Error: No logicle.h file

### ISSUE THREAD

**Issue by wmvoje** [bpteague/cytoflow#40]
Trying to install using pip on ubuntu 14.04. I get a fatal error:

`cytoflow/utility/logicle_ext/FastLogicle.cpp:1:21: fatal error: logicle.h: No such file or directory`

and the error:

`Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-OiGqUZ/cytoflow/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-RrwiKa-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-OiGqUZ/cytoflow/`

I tried to build both 0.3.0 and 0.3.2 and experienced the same thing.

**Comment by afrendeiro** [comment]
I had a similar issue and solved by installing `swig` system-wide: `sudo apt-get install swig`.

In addition, I had to remove the 4.4.0 version restriction on `pyface` (now using >=5.x) but I think this was an unrelated issue.

A third point blocking installation was `faulthandler` which should be removed from the requirements for Python 3 since it is part of the main libraries now.

**Comment by bpteague** [comment]
Hi @wmvoje and @afrendeiro  - sorry I haven't responded.
You shouldn't need swig, the interface files should be included in the distribution.  I'll double-check for this upcoming release.
Also, @afrendeiro , I don't expect this to work on Python 3+.  The last time I looked, at least one of the core libraries I depend on (traits, maybe? PyQt?) still required Python 2.  I'm pretty sure this will only work on Python 2.7.  I expect to move to Py3k when all the underlying libraries support it.

**Comment by danielmehnert** [comment]
Hi @bpteague! I still geht this error in a fresh debian installation. 
> cytoflow/utility/logicle_ext/FastLogicle.cpp:1:21: fatal error: logicle.h: No such file or directory
Is there any simple fix I can apply on my own?

**Comment by bpteague** [comment]
oh no!  i thought i fixed that!  lemme add it and spin another release.  hold on...

**Comment by bpteague** [comment]
@danielmehnert - I'm so sorry, I moved the location of the logicle sources and didn't update the MANIFEST file.  It should be fixed now -- do a `pip update` to get v0.5.2.  Please let me know (and re-open the bug) if it isn't!
